apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matf-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # uncomment or set according to your cluster
