global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/alert_rules.yml

scrape_configs:
  - job_name: 'multi-agent-testing-framework'
    metrics_path: /metrics
    static_configs:
      - targets: ['framework:3000']
