apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: stg-
namespace: matf-staging
resources:
  - ./namespace.yaml
  - ../../base
images:
  - name: ghcr.io/2faced0w0/multi_agent_testing_framework_prod
    newTag: latest
patches:
  - target:
      kind: Deployment
      name: multi-agent-testing-framework
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1