apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - redis.yaml
  - pvc.yaml
  - configmap.yaml
  - backup-cronjob.yaml
  - networkpolicy.yaml
